
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SOCKET_SERVER_URL = "dainty-shortbread-cd23d.netlify.app"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
